### ISSUE TITLE
chromeos update music plays but not radio

### ISSUE THREAD

**Issue by broomdodger** [Feverqwe/3pm-player#2]
acer c720 chromebook
ChromeOS 42.0.2311.87
With this new update to ChromeOS music still plays
but radio looks like it plays, the time increments
but there is no sound (it was working before the chromeos update)

**Comment by Feverqwe** [comment]
Thx! Fixed in 0.8.39.

**Comment by broomdodger** [comment]
Thank you.
0.8.39 radio works again.
